# Generated by Django 4.0.2 on 2022-05-12 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('DNI', models.IntegerField()),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('DNI', models.IntegerField()),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.EmailField(blank=True, max_length=254, null=True)),
                ('cargo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('DNI', models.IntegerField()),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.EmailField(blank=True, max_length=254, null=True)),
                ('profesorado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PersLimp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('DNI', models.IntegerField()),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.EmailField(blank=True, max_length=254, null=True)),
                ('turno', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppZero.alumno')),
                ('docente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppZero.docente')),
                ('materia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppZero.materia')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppZero.curso'),
        ),
    ]
