# Generated by Django 4.0.2 on 2022-05-12 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppZero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppZero.grado'),
        ),
        migrations.AddField(
            model_name='materia',
            name='grado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppZero.grado'),
        ),
    ]
