# Generated by Django 4.0.2 on 2022-05-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppZero', '0003_alter_curso_nivel_remove_materia_profesor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='profesor',
            name='especialidad',
            field=models.ManyToManyField(related_name='Profesorado', to='AppZero.Materia'),
        ),
    ]
