# Generated by Django 4.0.2 on 2022-05-05 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppZero', '0004_remove_profesor_especialidad_profesor_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppZero.alumno')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppZero.curso')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppZero.profesor')),
            ],
        ),
    ]
