# Generated by Django 4.0.2 on 2022-05-18 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppZero', '0005_alter_calificacion_cienciasnaturales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='alumno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AppZero.alumno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='calificaciones',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AppZero.calificacion'),
        ),
    ]
