# Generated by Django 4.0.2 on 2022-05-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppZero', '0006_calificacion_alumno_alter_alumno_calificaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='docente',
        ),
    ]
