# Generated by Django 4.0.2 on 2022-05-20 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppZero', '0007_remove_calificacion_alumno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='practlenguaje',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AppZero.nota'),
        ),
    ]
